CREATE DATABASE LEE;
USE LEE;
SHOW tables;
select * from lee_singles;

SELECT * FROM lee_singles LIMIT 5;

ALTER TABLE lee_singles
MODIFY COLUMN Month VARCHAR(200);

TRUNCATE TABLE lee_singles;

select * from lee_singles;

#KPI 1 
select count(*) as Total_Matches from lee_singles;

#VALIDATING ANY DUPLICATE VALUES!!
select ï»¿Match_Id, count(*) as Occurrences 
from lee_singles
group by ï»¿Match_Id
having count(*) > 1;

#VALIDATING ANY NULL VALUES!!
select
 sum(ï»¿Match_Id IS NULL) as Match_Null,
 sum(Date is Null) as Date_NUll,
 sum(tournament IS NULL) as Tournament_Null,
 sum(Tier Is Null) as Tier_Null,
 sum(round IS NULL)as Round_Null,
 sum(host_location IS null) as Host_Null
from lee_singles;

#VALIDATING MONTH VALUES!!
select distinct month from lee_singles order by month;

#VALIDATING TIER VALUES!!
select distinct tier from lee_singles order by tier;

#vVALIDATING ROUND VALUES!!
select distinct round from lee_singles order by round;

#VALIDATING RESULTS!!
select distinct result from lee_singles order by result;

#VALIDATING THAT THE SEPARATED YEAR AND MONTH ARE MATCHING THE DATE OR NOT!!
select * from lee_singles
where year(date)<>year or
month(date)<>month;

#KPI 2
Select count(result) as Total_Wins from lee_singles where result = "Win";

#KPI 3 
Select count(result) as Total_Loss from lee_singles where result = "Loss";

#KPI4
SELECT 
    ROUND(COUNT(CASE WHEN Result = 'Win' THEN 1 END) * 100.0 / COUNT(*),2) AS Overall_Win_Percentage
FROM lee_singles;

#KPI5
Select count(distinct Tournament) as Total_Tournament
from lee_singles;

#PERFORMANCE ANALYSIS 1 ( WIN BY YEAR)
SELECT 
 YEAR, COUNT(*) AS TOTAL_MATCHES,
 SUM(RESULT = "WIN") AS TOTAL_WINS,
 ROUND(SUM(CASE WHEN RESULT = "WIN" THEN 1 END)*100.0 / COUNT(*),2) AS WIN_PERCENTAGE
FROM LEE_SINGLES
GROUP BY YEAR
ORDER BY YEAR;

#PERFORMANCE ANALYSIS 2 ( WIN BY MONTH )
SELECT 
MONTH, COUNT(*) AS TOTAL_MATCH,
SUM( RESULT = "WIN" ) AS TOTAL_WINS,
ROUND(SUM(CASE WHEN RESULT = "WIN" THEN 1 END)*100.0/COUNT(*),2) AS WIN_RATE
FROM LEE_SINGLES
GROUP BY MONTH
ORDER BY MONTH;

#PERFORMANCE ANALYSIS ( TOURNAMENT WINS)
SELECT 
TOURNAMENT, COUNT(*) AS TOTAL_MATCHES,
SUM( RESULT = "WIN") AS TOTAL_WINS,
SUM( RESULT = "LOSS") AS TOTAL_LOSS,
ROUND(SUM(CASE WHEN RESULT = "WIN" THEN 1 ELSE 0 END)*100.0/COUNT(*),2) AS WIN_RATE
FROM LEE_SINGLES
GROUP BY TOURNAMENT 
ORDER BY TOTAL_MATCHES DESC;
# PERFORMANCE ANALYSIS ( TIER WISE PERFORMANCE)
SELECT 
TIER, COUNT(*) AS TOTAL_MATCHES,
SUM( RESULT = "WIN") AS TOTAL_WINS,
SUM( RESULT = "LOSS") AS TOTAL_LOSS,
ROUND(SUM(CASE WHEN RESULT = "WIN" THEN 1 ELSE 0 END)*100.0/COUNT(*),2) AS WIN_RATE
FROM LEE_SINGLES
GROUP BY TIER 
ORDER BY TOTAL_MATCHES DESC;

# PERFORMANCE ANALYSIS ( ROUND WISE WINS)
SELECT 
ROUND, COUNT(*) AS TOTAL_MATCHES,
SUM( RESULT = "WIN") AS TOTAL_WINS,
SUM( RESULT = "LOSS") AS TOTAL_LOSS,
ROUND(SUM(CASE WHEN RESULT = "WIN" THEN 1 ELSE 0 END)*100.0/COUNT(*),2) AS WIN_RATE
FROM LEE_SINGLES
GROUP BY ROUND 
ORDER BY TOTAL_MATCHES DESC;

#DEEPER ANALYSIS (OPPONENT VS LEE)
SELECT 
OPPONENT, COUNT(*) AS TOTAL_MATCHES,
SUM(RESULT = "WIN") AS TOTAL_WINS,
SUM(RESULT = "LOSS") AS TOTAL_LOSS,
ROUND(SUM(CASE WHEN RESULT ="WIN" THEN 1 ELSE 0 END)*100.0/ COUNT(*),2) AS WIN_RATE
FROM LEE_SINGLES
group by OPPONENT 
ORDER BY TOTAL_MATCHES DESC;

#DEEPER ANALYSIS (OPPONENT RECORD ANALYSIS)
SELECT 
OPPONENT, COUNT(*) AS TOTAL_MATCHES,
SUM(RESULT = "WIN") AS TOTAL_WINS,
SUM(RESULT = "LOSS") AS TOTAL_LOSS,
ROUND(SUM(CASE WHEN RESULT ="WIN" THEN 1 ELSE 0 END)*100.0/ COUNT(*),2) AS WIN_RATE
FROM LEE_SINGLES
group by OPPONENT
HAVING COUNT(*) >= 2 
ORDER BY WIN_RATE;

# DEEPER ANALYSIS (PERFORMANCE IN FINALS ANALYSIS)
SELECT 
ROUND, COUNT(*) AS TOTAL_MATCHES,
SUM(RESULT = "WIN") AS TOTAL_WINS,
SUM(RESULT = "LOSS") AS TOTAL_LOSS,
ROUND(SUM(CASE WHEN RESULT ="WIN" THEN 1 ELSE 0 END)*100.0/ COUNT(*),2) AS FINALS_WIN_RATE
FROM LEE_SINGLES
WHERE ROUND = "Final"
group by round;

# DEEPER ANALYSIS ( PERFORMANCE BY YEAR AND TIER)
SELECT 
YEAR,TIER,COUNT(*) AS TOTAL_MATCHES,
SUM(RESULT = "WIN") AS TOTAL_WINS,
SUM(RESULT = "LOSS") AS TOTAL_LOSS,
ROUND(SUM(CASE WHEN RESULT = "WIN" THEN 1 ELSE 0 END)*100.0/ COUNT(*),2) AS WIN_RATE
FROM LEE_SINGLES
GROUP BY YEAR, TIER
ORDER BY YEAR, TIER;	

# CTE ANALYSIS 
WITH LEE_STATS AS (
SELECT
TOURNAMENT,
COUNT(*) AS TOTAL_MATCHES,
SUM(CASE WHEN RESULT = "WIN" THEN 1 ELSE 0 END) AS TOTAL_WINS
FROM LEE_SINGLES
GROUP BY TOURNAMENT
HAVING COUNT(*) > 5
)
SELECT * 
FROM LEE_STATS
ORDER BY TOTAL_MATCHES DESC;

# CTE ANALYSIS 
WITH PLAYER_STAT AS(
SELECT 
TOURNAMENT,
COUNT(*) AS TOTAL_MATCHES,
SUM(RESULT = "WIN") AS TOTAL_WINS,
ROUND(SUM(CASE WHEN RESULT = "WIN" THEN 1 ELSE 0 END)*100.0/ COUNT(*),2) AS WIN_RATE
FROM LEE_SINGLES
GROUP BY TOURNAMENT
HAVING COUNT(*) >= 5
)
SELECT * FROM PLAYER_STAT WHERE WIN_RATE > 80
ORDER BY TOTAL_MATCHES DESC;

#WINDOW FUNCTION 
SELECT
ï»¿Match_Id,
YEAR,
RESULT,
COUNT(*) OVER (PARTITION BY YEAR) AS MATCHES_IN_YEAR
FROM LEE_SINGLES;

#WINDOW FUNCTION 
SELECT 
ï»¿Match_Id,
DATE,
YEAR,
RESULT,
ROW_NUMBER() OVER (ORDER BY DATE) AS MATCH_DATE
FROM LEE_SINGLES;

#WINDOW FUNCTION 
WITH LEE_TACS AS (
SELECT
TOURNAMENT,
YEAR,
COUNT(*) AS TOTAL_MATCHES
FROM LEE_SINGLES
GROUP BY TOURNAMENT, YEAR
)
SELECT *,
DENSE_RANK() OVER (ORDER BY TOTAL_MATCHES DESC) AS TOURNAMENT_RANK
FROM LEE_TACS;

#LAG FUNCTION 
SELECT
DATE,MONTH, YEAR, TOURNAMENT, OPPONENT,
LAG(OPPONENT) OVER (PARTITION BY YEAR ORDER BY DATE) AS PREVIOUS_OPPONENT
FROM LEE_SINGLES;

#LEAD 
SELECT
DATE, OPPONENT, RESULT,
LEAD(RESULT) OVER (ORDER BY DATE) AS NEXT_MATCH_RESULT
FROM LEE_SINGLES
ORDER BY DATE;